kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: relation-data-storage-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
