apiVersion: v1
kind: Service
metadata:
  name: relation-server-svc
  labels:
    app: django-relation-server
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: django-relation-server
    type: web
  type: ClusterIP
